In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
df=pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\NLP techadd\file_name.csv")
df.head()

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Text,Date Created
0,"No matter who someone is, how they look like, ...",Liberal,1,t5fybt,socialism,https://v.redd.it/ng5fyl7hp2l81,0,NaN,1.646272e+09
1,Biden speech draws 38.2 million U.S. TV viewers,Liberal,6,t5fqdn,democrats,https://www.reuters.com/world/us/biden-speech-...,1,NaN,1.646271e+09
2,State of the union,Liberal,1,t5fj9a,DemocraticSocialism,https://www.reddit.com/r/DemocraticSocialism/c...,1,Who watched the state of the union last night ...,1.646270e+09
3,We Should Just Give Poor People Money,Liberal,7,t5f7n9,SocialDemocracy,https://youtu.be/a80kRjpubG0,3,NaN,1.646270e+09
4,Do it for the Dew,Liberal,6,t5es2c,democrats,https://i.redd.it/drmunn90f2l81.jpg,1,NaN,1.646268e+09

In [5]:
df.describe()

              Score  Num of Comments  Date Created
count  12854.000000     12854.000000  1.285400e+04
mean     118.558270        19.055936  1.622576e+09
std      498.888034        60.381567  6.112838e+07
min        0.000000         0.000000  1.231048e+09
25%        3.000000         1.000000  1.632132e+09
50%       12.000000         3.000000  1.642030e+09
75%       65.000000        15.000000  1.645107e+09
max    25055.000000      2150.000000  1.646272e+09

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12854 entries, 0 to 12853
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            12854 non-null  str
 1   Political Lean   12854 non-null  str
 2   Score            12854 non-null  int64
 3   Id               12854 non-null  str
 4   Subreddit        12854 non-null  str
 5   URL              12854 non-null  str
 6   Num of Comments  12854 non-null  int64
 7   Text             2428 non-null   str
 8   Date Created     12854 non-null  float64
dtypes: float64(1), int64(2), str(6)
memory usage: 903.9 KB

In [7]:
df.shape

(12854, 9)

In [8]:
df.sample()

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Text,Date Created
4856,should Israel dismantle it's Iron dome defense...,Liberal,1,qvn11u,DemocraticSocialism,https://www.reddit.com/r/DemocraticSocialism/c...,6,\n\n[View Poll](https://www.reddit.com/poll/qv...,1.637111e+09

In [9]:
df.columns

Index(['Title', 'Political Lean', 'Score', 'Id', 'Subreddit', 'URL',
       'Num of Comments', 'Text', 'Date Created'],
      dtype='str')

In [10]:
df.index

RangeIndex(start=0, stop=12854, step=1)

In [11]:
df.dtypes

Title                  str
Political Lean         str
Score                int64
Id                     str
Subreddit              str
URL                    str
Num of Comments      int64
Text                   str
Date Created       float64
dtype: object

In [ ]:
df.isnall().sum()