In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
df=pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\NLP techadd\file_name.csv")
df.head()

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Text,Date Created
0,"No matter who someone is, how they look like, ...",Liberal,1,t5fybt,socialism,https://v.redd.it/ng5fyl7hp2l81,0,NaN,1.646272e+09
1,Biden speech draws 38.2 million U.S. TV viewers,Liberal,6,t5fqdn,democrats,https://www.reuters.com/world/us/biden-speech-...,1,NaN,1.646271e+09
2,State of the union,Liberal,1,t5fj9a,DemocraticSocialism,https://www.reddit.com/r/DemocraticSocialism/c...,1,Who watched the state of the union last night ...,1.646270e+09
3,We Should Just Give Poor People Money,Liberal,7,t5f7n9,SocialDemocracy,https://youtu.be/a80kRjpubG0,3,NaN,1.646270e+09
4,Do it for the Dew,Liberal,6,t5es2c,democrats,https://i.redd.it/drmunn90f2l81.jpg,1,NaN,1.646268e+09

In [4]:
df.describe()

              Score  Num of Comments  Date Created
count  12854.000000     12854.000000  1.285400e+04
mean     118.558270        19.055936  1.622576e+09
std      498.888034        60.381567  6.112838e+07
min        0.000000         0.000000  1.231048e+09
25%        3.000000         1.000000  1.632132e+09
50%       12.000000         3.000000  1.642030e+09
75%       65.000000        15.000000  1.645107e+09
max    25055.000000      2150.000000  1.646272e+09

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12854 entries, 0 to 12853
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            12854 non-null  str
 1   Political Lean   12854 non-null  str
 2   Score            12854 non-null  int64
 3   Id               12854 non-null  str
 4   Subreddit        12854 non-null  str
 5   URL              12854 non-null  str
 6   Num of Comments  12854 non-null  int64
 7   Text             2428 non-null   str
 8   Date Created     12854 non-null  float64
dtypes: float64(1), int64(2), str(6)
memory usage: 903.9 KB

In [6]:
df.shape

(12854, 9)

In [7]:
df.sample()

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Text,Date Created
2605,Julian Assange Wins Right to Appeal Extraditio...,Liberal,39,sbow7u,alltheleft,https://www.democracynow.org/2022/1/24/julian_...,3,NaN,1.643039e+09

In [8]:
df.columns

Index(['Title', 'Political Lean', 'Score', 'Id', 'Subreddit', 'URL',
       'Num of Comments', 'Text', 'Date Created'],
      dtype='str')

In [9]:
df.index

RangeIndex(start=0, stop=12854, step=1)

In [10]:
df.dtypes

Title                  str
Political Lean         str
Score                int64
Id                     str
Subreddit              str
URL                    str
Num of Comments      int64
Text                   str
Date Created       float64
dtype: object

In [11]:
df.notnull()
df.isna().sum()

Title                  0
Political Lean         0
Score                  0
Id                     0
Subreddit              0
URL                    0
Num of Comments        0
Text               10426
Date Created           0
dtype: int64

In [12]:
df['Text'].isna().mean()*100

np.float64(81.11093822934495)

In [13]:
df=df.drop('Text',axis=True)

In [14]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [15]:
stopwords = stopwords.words('english')
stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [16]:
lemmatizer = WordNetLemmatizer()

In [ ]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+"," ",text)
    text = re.sub(r"[a-zA-Z\s]"," ",text)
    words = word_tokenize(text)

    words = [word for word in words if word not in stopwords]

    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [34]:
clean_text

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    stop_words='english',
    min_df=2
)
X = tfidf.fit_transform('clean_text')

ValueError: Iterable over raw text documents expected, string object received.

In [29]:
X = tfidf.fit_transform(df['clean_text'])

KeyError: 'clean_text'

In [23]:
df.head(5)

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Date Created
0,"No matter who someone is, how they look like, ...",Liberal,1,t5fybt,socialism,https://v.redd.it/ng5fyl7hp2l81,0,1.646272e+09
1,Biden speech draws 38.2 million U.S. TV viewers,Liberal,6,t5fqdn,democrats,https://www.reuters.com/world/us/biden-speech-...,1,1.646271e+09
2,State of the union,Liberal,1,t5fj9a,DemocraticSocialism,https://www.reddit.com/r/DemocraticSocialism/c...,1,1.646270e+09
3,We Should Just Give Poor People Money,Liberal,7,t5f7n9,SocialDemocracy,https://youtu.be/a80kRjpubG0,3,1.646270e+09
4,Do it for the Dew,Liberal,6,t5es2c,democrats,https://i.redd.it/drmunn90f2l81.jpg,1,1.646268e+09

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(df['Political Lean'])
y

array([1, 1, 1, ..., 0, 0, 0], shape=(12854,))

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size,random_state=42)

NameError: name 'x' is not defined