In [1]:
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kashi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\NLP techadd\bbc_data.csv")
df.head()

                                                data         labels
0  Musicians to tackle US red tape  Musicians gro...  entertainment
1  U2s desire to be number one  U2, who have won ...  entertainment
2  Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3  Snicket tops US box office chart  The film ada...  entertainment
4  Oceans Twelve raids box office  Oceans Twelve,...  entertainment

In [3]:
df.tail()

                                                   data labels
2220  Warning over Windows Word files  Writing a Mic...   tech
2221  Fast lifts rise into record books  Two high-sp...   tech
2222  Nintendo adds media playing to DS  Nintendo is...   tech
2223  Fast moving phone viruses appear  Security fir...   tech
2224  Hacker threat to Apples iTunes  Users of Apple...   tech

In [4]:
df.columns

Index(['data', 'labels'], dtype='str')

In [5]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
from nltk.corpus import stopwords

In [6]:
stopword = stopwords.words('english')
stopword

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [7]:
corpus=[]
for i in range(0,len(df)):
    review = df['data'][i]
    review = re.sub('[^a-zA-Z]',' ',review)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if  not word in stopword]
    review=' '.join(review)
    corpus.append(review)

In [8]:
corpus

['musician tackl us red tape musician group tackl us visa regul blame hinder british act chanc succeed across atlant singer hope perform us expect pay xc xa simpli obtain visa group includ musician union call end raw deal face british perform us act face compar expens bureaucraci visit uk promot purpos nigel mccune musician union said british musician disadvantag compar us counterpart sponsor make petit behalf form amount nearli page musician face tougher regul athlet journalist make mistak form risk five year ban thu abil career say mr mccune us world biggest music market mean someth done creaki bureaucraci say mr mccune current situat prevent british act maintain momentum develop us ad musician union stanc endors music manag forum mmf say british artist face uphil struggl succeed us thank tough visa requir also seen impract mmf gener secretari jame seller said imagin orchestra orkney everi member would travel london visa process us market seen holi grail one benchmark success still go fight get still import market like europ india china ad mr seller depart media cultur sport spokeswoman said awar peopl experienc problem work us embassi record industri see us embassi spokesman said awar entertain requir visa time specif visa everyth process applic speedili awar import cultur exchang best facilit ad',
 'u desir number one u three prestigi grammi award hit vertigo stubbornli cling statu one biggest band world popular group histori rock sever thing common music must inspir appeal across gener distinct alway groundbreak success music compel perform charismat intellig enough make good decis keep feet ground also want want biggest band ever stop want beatl roll stone still rem hold onto queen catsuit u spade keep churn new album dismantl atom bomb come year schoolfriend got togeth dublin year joshua tree cement place time rock list may lost edgi raw youth forc propel top lost none desir abil craft song album vertigo first singl new album went straight uk singl chart number one knock eminem top spot give th top hit challeng bigger bolder better make record whole world listen bono recent said drummer larri mullen jr echo sentiment competit want radio big singl dont want thought veteran band band done everyth consider power ensur remain biggest band world accord q magazin editor paul ree make huge determin formid ad equal determin push make music continu stand theyv constantli invent challeng perhap alon rock band got better age key ingredi fact highli organis mr ree said everyth right way group born mullen put appeal bandmat high school notic board attract fellow pupil paul hewson bono vocal adam clayton bass david evan edg guitar brother dick dick evan soon drop four piec known feedback hype settl u talent contest got notic manag paul mcguin brilliant coars mcguin recent said way exactli badli struggl attract record compani attent later describ pretti damn averag strang eeri scout saw live releas two ireland singl top nation chart lead deal island debut album boy stadium fill anthem sound u aim start third album war saw make breakthrough side atlant go number one uk us song like sunday bloodi sunday new year day brought success imag polit spiritu band bono reject clich stage perform includ flag wave speaker climb drum throw earn reput electr perform appear live aid wide seen seal global stardom joshua tree broke sale record saw band reach height power hit includ street name still havent found im look without song took band epic atmospher sound simpl power popular pinnacl end decad mark crucial point band reach top still yearn new challeng achiev came form explor differ branch rock foray electron danc music plu wildli extravag stage show still tri retain mass appeal achtung babi album follow zooropa pop correspond stadium tour featur giant oliv fli car live phone call white hous bono transform alter ego fli macphisto also build parallel reput alway pleasur bandmat campaign issu global debt aid releas dismantl atom bomb sold million album around world still want',
 'rocker doherti stage fight rock singer pete doherti involv fight band guitarist biggest gig date babyshambl play fan london brixton academi tuesday former libertin singer trade blow guitarist patrick walden separ bundl stage return end set show earlier held due audienc overcrowd monday doherti face blackmail robberi charg court deni xc xa bail judg agre extend gmt curfew deadlin two hour could play brixton gig babyshambl form acrimoni departur libertin play warm show garag north london monday tuesday doherti three bandmat introduc crowd mick jone former clash guitarist produc libertin second album babyshambl took stage frenzi recept gmt launch last singl killamangiro reach number eight decemb group stop next song persuad fan push forward allow secur guard pull peopl crush doherti appeal fan calm say there peopl get hurt front youv got move back music resum minut later sever song singer appear accident disconnect walden guitar lead pair trade kick punch bouncer step band left stage return five minut finish minut perform troubl doherti home midnight observ curfew one condit bail monday judg agre allow perform condit request chang bail term regular occurr singer arrest fellow musician alan wass februari alleg disput documentari maker max carlish london hotel next due court april',
 'snicket top us box offic chart film adapt lemoni snicket novel top north america box offic chart displac ocean seri unfortun event star jim carrey took xc xa debut weekend ocean fell number two new entri spanglish enter chart number three take xc xa seri unfortun event also star scottish comedian billi connelli carrey take number differ role surreal film new entri top make flight phoenix number eight star denni quaid carrey entertain crowd uk premier lemoni snicket london friday actor grab co star meryl streep whisk around leicest squar base cult children book author daniel handler film follow three children orphan parent die fire taken wick uncl count olaf play carrey scheme get hand fortun',
 'ocean twelv raid box offic ocean twelv crime caper sequel star georg clooney brad pitt julia robert gone straight number one us box offic chart took xc xa weekend ticket sale accord studio estim sequel follow master crimin tri pull three major heist across europ knock last week number one nation treasur third place wesley snipe blade triniti second take xc xa round top five anim fabl polar express star tom hank festiv comedi christma krank ocean twelv box offic triumph mark fourth biggest open decemb releas us three film lord ring trilog sequel narrowli beat predecessor ocean eleven took xc xa open weekend xc xa total remak film star frank sinatra rat pack ocean eleven direct oscar win director steven soderbergh soderbergh return direct hit sequel reunit clooney pitt robert matt damon andi garcia elliott gould catherin zeta jone join star cast fun good holiday movi said dan fellman presid distribut warner bro howev us critic less complimentari xc xa project lo angel time label dispirit vaniti project milder review new york time dub sequel unabashedli trivial',
 'landmark movi hail us film profession declar fahrenheit passion christ two signific cultur mileston american film institut afi hail mel gibson biblic epic michael moor polit documentari inspir nation debat claim film maker toss hollywood convent window institut also cite death actor marlon brando chang landscap tv news us refer marlon brando death juli age strong afi juri conclud art screen act two chapter brando brando credit screen legend raw hypnot energi abil creat charact like stanley kowalski terri malloy live forev annal film histori list also acknowledg key influenc trend world film broadcast among current trend highlight final broadcast veteran newscast tom brokaw barbara walter impend retir cb news anchor dan rather place afi fear news landscap newscast person journalist balanc integr increasingli ignor afi also question long term viabil even news broadcast light hour news channel internet list also draw attent grow influenc us broadcast regul feder commun commiss fcc institut conclud threat regul went freefal follow janet jackson wardrob malfunct live super bowl perform februari profound effect televis unsur fcc rule issu creativ commun begun self censor show disturb trend countri found free express afi juri declar illustr point afi cite abc affili refus air steven spielberg film save privat ryan unedit form fear possibl fine',
 'pete doherti miss bail deadlin singer pete doherti spend weekend jail could come xc xa bond money bail time former libertin singer grant bail curfew restrict highburi corner magistr court charg robberi blackmail lawyer said money could rais time mr doherti arrest follow alleg incid london hotel wednesday even musician alan wass also north london appear court accus offenc magistr impos rang bail condit mr doherti includ curfew except attend drug rehabilit centr told would abl leav home without accompani secur firm must also surrend passport report daili local polic station mr wass also given curfew told surrend passport mr doherti left libertin end june continu perform band babyshambl singer link supermodel kate moss arrest polic call islington hotel respons claim man assault man later taken univers colleg hospit london facial injuri discharg lawyer repres mr doherti mr wass said outsid court pair strenuous deni charg',
 'focker retain film chart crown comedi meet focker held number one spot north american box offic second week took xc xa weekend make overal take xc xa day accord studio estim took xc xa christma day alon highest take day box offic histori sequel ben stiller comedi meet parent star robert de niro dustin hoffman barbra streisand success meet focker could help produc record box offic revenu said paul dergarabedian presid industri tracker exhibitor relat weve much stronger anticip final week year help industri end high note said mr dergarabedian meet focker also broke box offic record money taken new year eve made xc xa new year day took xc xa previou new year eve record set cast away xc xa lord ring return king held new year day titl xc xa howev christma take figur blame christma fall weekend year weekend top film took estim xc xa increas weekend last year major releas last week provid competit meet focker lemoni snicket seri unfortun event finish second place xc xa aviat star leonardo dicaprio howard hugh end third posit take xc xa comedi fat albert co written bill cosbi move chart fourth place take xc xa',
 'top gig award scissor sister new york band scissor sister gig year award perform year v festiv award vote listen virgin radio compil top mostli domin newcom music scene year quirki disco rock band beat red hot chili pepper came second hyde park perform june virgin radio dj pete mitchel said year seen amaz array talent come mainstream ad scissor sister one origin eccentr band come surpris british public lap perform newcom kean came third place august gig v festiv follow maroon snow patrol music veteran david bowi earn place list number eight respect number seven oxfam make fair trade gig london hammersmith apollo octob featur perform rem razorlight coldplay chri martin glasgow franz ferdinand earn place number nine home town perform april annual survey vote nearli listen',
 'johnni depp act outlaw johnni depp whose latest role peter pan creator jm barri find neverland celebr one hollywood maverick talent depp becom unlik major star given prefer take dark idiosyncrat role instead surefir box offic hit long run work relationship equal unconvent director tim burton depp born kentucki first want rock star play number band support act iggi pop b florida visit lo angel former wife introduc actor nicola cage start film career play doom teenag horror film nightmar elm street two year later play soldier oliv stone vietnam epic platoon tv first made depp star play undercov cop tommi hanson us seri jump street three year began partnership burton dark fairi tale edward scissorhand young man blade hand plaudit downbeat film what eat gilbert grape play sensit youth look overweight mother retard younger brother play leonardo dicaprio anoth role burton ed wood star depp craze cult film maker wood play much seriou sensit role next major film donni brasco portray undercov cop infiltr mafia ring direct film date brave stori indian man offer money appear snuff film two year later play hunter thompson terri gilliam ambiti poorli receiv big screen adapt fear loath la vega work tim burton horror film sleepi hollow appear opposit dame judi dench juliett binoch chocolat perform pirat caribbean earn golden globe bafta nomin mani critic think base upon manner friend roll stone guitarist keith richard latest role find neverland explor jm barri relationship sylvia kate winslet children depp charismat perform drew audienc adult children alik barri vivid imagin call fifth child group film director marc forster two children french singer vanessa paradi previous long term relationship british model kate moss theme children literatur depp career long associ tim burton set continu next role play willi wonka remak roald dahl classic charli chocol factori british tv comedi fan might also rememb depp guest role final episod bbc sketch programm fast show cite favourit show anoth surpris move depp vari intrigu career',
 'actress robert take spider role actress julia robert play part spider new film version children classic charlott web voic charlott team girl save friend wilbur pig stori eb white film mix live action anim robert first project sinc birth twin hazel phinnaeu two month ago oprah winfrey voic goos john clees voic sheep steve buscemi rat film ten year old dakota fan play fern girl centr stori film direct go film maker gari winick film due begin melbourn australia later month charlott web sold million copi sinc publish anim version made first live action film actor voic wilbur pig yet reveal',
 'film product fall uk number british film produc uk fell movi star johnni depp jude law among affect screen daili said twenti seven british film made uk last year follow drop fund compar accord trade weekli attribut drop tighter tax law reduc fund sourc nation lotteri uk us co product britain fell last year last year govern close tax loophol mani film investor taken advantag fund film uk sever project shelv face implic clampdown coupl reduct movi fund tradit sourc includ lotteri miramax film shoot period drama tulip fever star jude law keira knightley postpon indefinit shoot libertin star johnni depp move isl man isnt anyth come replac fund said libertin execut produc marc samuelson hiatu film medium budget xc xa similar level box offic hit vera drake calendar girl endur love expect worst hit tax clampdown strength pound dollar expect result fall number us film shot uk screen intern ad big budget co product harri potter seri continu shot uk howev uk film council said drop partli due especi good year british film product bridget jone edg reason wimbledon thunderbird film uk drop expect way record level product could better council spokesperson said reduct indigen film product due varieti factor includ continu long term trend toward co product film one countri chang financ arrang earli predict whether downward trend uk product would continu throughout uk film council said septemb govern introduc subsidi worth xc xa per film medium budget film new treasuri measur also due announc replac uk film tax relief scheme section juli',
 'patti smith host art festiv rock star patti smith made artist director year meltdown festiv held london south bank centr june punk pioneer follow morrissey david bowi nick cave direct day concert event smith yet decid line meltdown begin june want touch aspect cultur perhap read genet idea jeremi iron read proust said year old us singer night told observ newspap festiv would respons materi exploit greedi time import explor new also salut best art aesthet spiritu said last year meltdown festiv direct ex smith star morrissey includ appear singer jane birkin nanci sinatra playwright alan bennett also persuad punk band new york doll reform reunion show',
 'brit return kean number one brit success help return kean award win album hope fear back top uk album chart debut album took best british album titl brit tuesday move seven place number eight number one also capitalis brit success scissor sister whose eponym album move three place number two u latest singl sometim cant make took top spot singl chart ahead elvi track current album dismantl atom bomb push eminem like toy soldier number one number three elvi wooden heart enter chart number two sixth seri reissu mark th anniversari presley birth current six releas elvi track occupi spot top singl chart includ lonesom tonight number never number jailhous rock number soldier destini child ti lil wayn debut number four almost duet former westlif star brian mcfadden delta goodrem fell number three number five follow brit success franz ferdinand best rock act best british group last week self titl album move number four last week number one album tourist athlet fell number three',
 'sundanc honour foreign film intern film given promin us film next year sundanc film festiv movi domin theme war independ film festiv featur two new intern cinema competit januari season utah forti two film debut sundanc includ liberac baghdad british director sean mcallist prestigi festiv found actor robert redford alway intern compon next year enter juri competit festiv director geoffrey gilmor said want give world cinema emphasi put par american dramat documentari competit twelv film compet new world cinema documentari categori focu countri peopl sieg liberac baghdad featur iraqi pianist hide hotel wait visa finnish film three room melancholia look war chechnya shake hand devil journey romeo dallair tell un mission rwanda genocid french isra product wall look israel controversi secur wall separ palestinian territori film compet new world cinema dramat categori includ work germani south korea angola china denmark australia sever hollywood star featur festiv american independ drama categori includ keanu reev benjamin bratt vinc vaughn star quirki movi thumbsuck gram actress naomi watt play bud hollywood actress elli parker top grand juri prize year festiv went low budget sci fi thriller primer written direct shane carruth morgan spurlock earn direct award super size becam intern box offic hit',
 'rapper snoop dogg su rape us rapper snoop dogg su xc xa make artist claim entourag drug rape two year ago woman said assault record jimmi kimmel live tv show abc network rapper spokesman said alleg untru woman misus legal system mean extract financi gain abc said claim merit star charg polic lawsuit file lo angel friday say woman champagn spike assault rapper spokesperson said snoop opportun prove court law alleg victim opportunist deceit confid case alleg victim claim snoop dogg reject lawsuit name snoop dogg real name calvin broadu plu three associ walt disney compani parent compani abc inc woman wait two year sue tri negoti settlement media compani lawyer perri wander said disney abc fail provid safe work environ client said legal action come rap star su woman claim tri blackmail keep quiet alleg assault year old rapper enjoy six us top album sinc burst onto music scene hit song like what name gin juic',

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,ngram_range=(1,2))
x = cv.fit_transform(corpus)

In [10]:
import numpy as np
np.set_printoptions(edgeitems=40,linewidth=100000,formatter=dict(float=lambda x:"%.3g"% x))
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 268012 stored elements and shape (2225, 2500)>

In [11]:
cv.vocabulary_

{'musician': np.int64(1458),
 'tackl': np.int64(2186),
 'us': np.int64(2339),
 'red': np.int64(1789),
 'tape': np.int64(2196),
 'group': np.int64(977),
 'visa': np.int64(2369),
 'regul': np.int64(1802),
 'blame': np.int64(233),
 'british': np.int64(273),
 'act': np.int64(16),
 'chanc': np.int64(347),
 'succeed': np.int64(2154),
 'across': np.int64(15),
 'singer': np.int64(2014),
 'hope': np.int64(1049),
 'perform': np.int64(1612),
 'expect': np.int64(771),
 'pay': np.int64(1597),
 'xc': np.int64(2481),
 'xa': np.int64(2477),
 'simpli': np.int64(2011),
 'includ': np.int64(1096),
 'union': np.int64(2326),
 'call': np.int64(296),
 'end': np.int64(713),
 'deal': np.int64(543),
 'face': np.int64(786),
 'compar': np.int64(426),
 'expens': np.int64(772),
 'visit': np.int64(2371),
 'uk': np.int64(2318),
 'promot': np.int64(1715),
 'purpos': np.int64(1737),
 'said': np.int64(1893),
 'make': np.int64(1333),
 'form': np.int64(874),
 'amount': np.int64(85),
 'nearli': np.int64(1467),
 'page': np.int64(1572),
 'athlet': np.int64(140),
 'journalist': np.int64(1189),
 'mistak': np.int64(1410),
 'risk': np.int64(1857),
 'five': np.int64(854),
 'year': np.int64(2486),
 'ban': np.int64(176),
 'abil': np.int64(0),
 'career': np.int64(318),
 'say': np.int64(1915),
 'mr': np.int64(1435),
 'world': np.int64(2454),
 'biggest': np.int64(224),
 'music': np.int64(1454),
 'market': np.int64(1352),
 'mean': np.int64(1366),
 'someth': np.int64(2048),
 'done': np.int64(634),
 'current': np.int64(525),
 'situat': np.int64(2020),
 'prevent': np.int64(1685),
 'maintain': np.int64(1331),
 'develop': np.int64(590),
 'ad': np.int64(23),
 'manag': np.int64(1339),
 'forum': np.int64(880),
 'artist': np.int64(127),
 'struggl': np.int64(2141),
 'thank': np.int64(2225),
 'tough': np.int64(2274),
 'requir': np.int64(1827),
 'also': np.int64(74),
 'seen': np.int64(1952),
 'gener': np.int64(928),
 'secretari': np.int64(1944),
 'jame': np.int64(1171),
 'imagin': np.int64(1085),
 'everi': np.int64(754),
 'member': np.int64(1375),
 'would': np.int64(2464),
 'travel': np.int64(2287),
 'london': np.int64(1304),
 'process': np.int64(1702),
 'one': np.int64(1535),
 'success': np.int64(2155),
 'still': np.int64(2118),
 'go': np.int64(949),
 'fight': np.int64(831),
 'get': np.int64(937),
 'import': np.int64(1091),
 'like': np.int64(1287),
 'europ': np.int64(746),
 'india': np.int64(1105),
 'china': np.int64(367),
 'depart': np.int64(572),
 'media': np.int64(1371),
 'cultur': np.int64(522),
 'sport': np.int64(2085),
 'spokeswoman': np.int64(2084),
 'awar': np.int64(164),
 'peopl': np.int64(1606),
 'experienc': np.int64(774),
 'problem': np.int64(1701),
 'work': np.int64(2452),
 'record': np.int64(1786),
 'industri': np.int64(1111),
 'see': np.int64(1948),
 'spokesman': np.int64(2082),
 'entertain': np.int64(728),
 'time': np.int64(2254),
 'specif': np.int64(2074),
 'everyth': np.int64(758),
 'applic': np.int64(108),
 'exchang': np.int64(765),
 'best': np.int64(213),
 'xc xa': np.int64(2482),
 'five year': np.int64(856),
 'say mr': np.int64(1916),
 'spokesman said': np.int64(2083),
 'desir': np.int64(578),
 'number': np.int64(1509),
 'three': np.int64(2243),
 'grammi': np.int64(964),
 'award': np.int64(165),
 'hit': np.int64(1035),
 'statu': np.int64(2109),
 'band': np.int64(177),
 'popular': np.int64(1657),
 'histori': np.int64(1034),
 'rock': np.int64(1864),
 'sever': np.int64(1980),
 'thing': np.int64(2233),
 'common': np.int64(422),
 'must': np.int64(1460),
 'inspir': np.int64(1126),
 'appeal': np.int64(104),
 'alway': np.int64(78),
 'intellig': np.int64(1134),
 'enough': np.int64(725),
 'good': np.int64(956),
 'decis': np.int64(552),
 'keep': np.int64(1197),
 'ground': np.int64(976),
 'want': np.int64(2385),
 'ever': np.int64(753),
 'stop': np.int64(2123),
 'roll': np.int64(1868),
 'stone': np.int64(2122),
 'hold': np.int64(1038),
 'onto': np.int64(1538),
 'queen': np.int64(1745),
 'new': np.int64(1475),
 'album': np.int64(62),
 'bomb': np.int64(250),
 'come': np.int64(409),
 'got': np.int64(960),
 'togeth': np.int64(2260),
 'dublin': np.int64(664),
 'place': np.int64(1631),
 'list': np.int64(1293),
 'may': np.int64(1363),
 'lost': np.int64(1314),
 'forc': np.int64(869),
 'top': np.int64(2269),
 'song': np.int64(2051),
 'first': np.int64(848),
 'singl': np.int64(2015),
 'went': np.int64(2410),
 'straight': np.int64(2127),
 'chart': np.int64(357),
 'knock': np.int64(1215),
 'spot': np.int64(2086),
 'give': np.int64(941),
 'th': np.int64(2223),
 'challeng': np.int64(342),
 'bigger': np.int64(223),
 'better': np.int64(219),
 'whole': np.int64(2420),
 'listen': np.int64(1294),
 'recent': np.int64(1782),
 'competit': np.int64(429),
 'radio': np.int64(1754),
 'big': np.int64(222),
 'dont': np.int64(635),
 'thought': np.int64(2239),
 'veteran': np.int64(2354),
 'consider': np.int64(452),
 'power': np.int64(1668),
 'ensur': np.int64(726),
 'remain': np.int64(1813),
 'accord': np.int64(9),
 'magazin': np.int64(1327),
 'editor': np.int64(691),
 'paul': np.int64(1596),
 'huge': np.int64(1065),
 'determin': np.int64(587),
 'equal': np.int64(734),
 'push': np.int64(1739),
 'continu': np.int64(468),
 'stand': np.int64(2101),
 'invent': np.int64(1144),
 'perhap': np.int64(1613),
 'alon': np.int64(70),
 'age': np.int64(46),
 'key': np.int64(1204),
 'fact': np.int64(788),
 'highli': np.int64(1028),
 'organis': np.int64(1554),
 'right': np.int64(1853),
 'way': np.int64(2395),
 'born': np.int64(256),
 'put': np.int64(1740),
 'high': np.int64(1022),
 'school': np.int64(1924),
 'notic': np.int64(1505),
 'board': np.int64(245),
 'attract': np.int64(148),
 'fellow': np.int64(820),
 'pupil': np.int64(1735),
 'adam': np.int64(24),
 'david': np.int64(539),
 'edg': np.int64(688),
 'brother': np.int64(279),
 'soon': np.int64(2053),
 'drop': np.int64(659),
 'four': np.int64(886),
 'piec': np.int64(1626),
 'known': np.int64(1217),
 'settl': np.int64(1976),
 'talent': np.int64(2194),
 'contest': np.int64(467),
 'exactli': np.int64(761),
 'badli': np.int64(171),
 'compani': np.int64(424),
 'attent': np.int64(145),
 'later': np.int64(1240),
 'describ': np.int64(575),
 'pretti': np.int64(1684),
 'averag': np.int64(161),
 'saw': np.int64(1914),
 'live': np.int64(1296),
 'releas': np.int64(1810),
 'two': np.int64(2314),
 'ireland': np.int64(1154),
 'nation': np.int64(1464),
 'lead': np.int64(1248),
 'island': np.int64(1158),
 'debut': np.int64(548),
 'boy': np.int64(262),
 'stadium': np.int64(2097),
 'fill': np.int64(836),
 'sound': np.int64(2057),
 'aim': np.int64(56),
 'start': np.int64(2104),
 'third': np.int64(2235),
 'war': np.int64(2386),
 'breakthrough': np.int64(267),
 'side': np.int64(2001),
 'sunday': np.int64(2164),
 'day': np.int64(540),
 'brought': np.int64(280),
 'imag': np.int64(1084),
 'polit': np.int64(1650),
 'reject': np.int64(1805),
 'stage': np.int64(2099),
 'wave': np.int64(2394),
 'speaker': np.int64(2072),
 'throw': np.int64(2248),
 'earn': np.int64(676),
 'reput': np.int64(1825),
 'electr': np.int64(702),
 'appear': np.int64(105),
 'aid': np.int64(55),
 'wide': np.int64(2424),
 'seal': np.int64(1935),
 'global': np.int64(945),
 'broke': np.int64(277),
 'sale': np.int64(1908),
 'reach': np.int64(1768),
 'street': np.int64(2131),
 'name': np.int64(1462),
 'havent': np.int64(1002),
 'found': np.int64(883),
 'im': np.int64(1083),
 'look': np.int64(1308),
 'without': np.int64(2445),
 'took': np.int64(2267),
 'simpl': np.int64(2010),
 'decad': np.int64(549),
 'mark': np.int64(1351),
 'crucial': np.int64(520),
 'point': np.int64(1647),
 'achiev': np.int64(12),
 'came': np.int64(297),
 'explor': np.int64(778),
 'differ': np.int64(596),
 'electron': np.int64(703),
 'danc': np.int64(531),
 'plu': np.int64(1644),
 'show': np.int64(1997),
 'tri': np.int64(2292),
 'retain': np.int64(1842),
 'mass': np.int64(1356),
 'babi': np.int64(167),
 'follow': np.int64(865),
 'pop': np.int64(1655),
 'correspond': np.int64(488),
 'tour': np.int64(2275),
 'featur': np.int64(813),
 'giant': np.int64(938),
 'oliv': np.int64(1531),
 'fli': np.int64(860),
 'car': np.int64(314),
 'phone': np.int64(1620),
 'white': np.int64(2419),
 'hous': np.int64(1055),
 'build': np.int64(286),
 'campaign': np.int64(301),
 'issu': np.int64(1161),
 'debt': np.int64(547),
 'sold': np.int64(2043),
 'million': np.int64(1397),
 'around': np.int64(119),
 'number one': np.int64(1510),
 'dont want': np.int64(638),
 'new year': np.int64(1477),
 'around world': np.int64(120),
 'involv': np.int64(1149),
 'gig': np.int64(939),
 'date': np.int64(534),
 'play': np.int64(1636),
 'fan': np.int64(802),
 'academi': np.int64(5),
 'tuesday': np.int64(2307),
 'former': np.int64(877),
 'trade': np.int64(2281),
 'blow': np.int64(237),
 'separ': np.int64(1964),
 'return': np.int64(1844),
 'set': np.int64(1975),
 'earlier': np.int64(672),
 'held': np.int64(1013),
 'due': np.int64(665),
 'audienc': np.int64(150),
 'monday': np.int64(1417),
 'charg': np.int64(352),
 'court': np.int64(501),
 'deni': np.int64(571),
 'judg': np.int64(1190),
 'agre': np.int64(51),
 'extend': np.int64(781),
 'gmt': np.int64(948),
 'hour': np.int64(1054),
 'could': np.int64(491),
 'north': np.int64(1500),
 'introduc': np.int64(1143),
 'crowd': np.int64(518),
 'jone': np.int64(1186),
 'clash': np.int64(383),
 'produc': np.int64(1704),
 'second': np.int64(1941),
 'launch': np.int64(1243),
 'last': np.int64(1235),
 'eight': np.int64(697),
 'decemb': np.int64(550),
 'next': np.int64(1485),
 'persuad': np.int64(1616),
 'forward': np.int64(881),
 'allow': np.int64(68),
 'secur': np.int64(1947),
 'pull': np.int64(1733),
 'there': np.int64(2230),
 'hurt': np.int64(1071),
 'front': np.int64(902),
 'move': np.int64(1429),
 'back': np.int64(168),
 'minut': np.int64(1408),
 'pair': np.int64(1574),
 'kick': np.int64(1206),
 'step': np.int64(2113),
 'left': np.int64(1259),
 'finish': np.int64(845),
 'troubl': np.int64(2302),
 'home': np.int64(1044),
 'observ': np.int64(1514),
 'condit': np.int64(441),
 'request': np.int64(1826),
 'chang': np.int64(349),
 'term': np.int64(2216),
 'regular': np.int64(1803),
 'arrest': np.int64(122),
 'alan': np.int64(61),
 'februari': np.int64(814),
 'alleg': np.int64(65),
 'disput': np.int64(617),
 'documentari': np.int64(625),
 'maker': np.int64(1335),
 'hotel': np.int64(1053),
 'april': np.int64(113),
 'box': np.int64(260),
 'offic': np.int64(1523),
 'film': np.int64(837),
 'adapt': np.int64(25),
 'novel': np.int64(1506),
 'america': np.int64(81),
 'seri': np.int64(1967),
 'unfortun': np.int64(2325),
 'event': np.int64(751),
 'star': np.int64(2103),
 'weekend': np.int64(2405),
 'fell': np.int64(819),
 'entri': np.int64(730),
 'enter': np.int64(727),
 'take': np.int64(2189),
 'scottish': np.int64(1931),
 'role': np.int64(1867),
 'flight': np.int64(862),
 'premier': np.int64(1674),
 'friday': np.int64(899),
 'actor': np.int64(20),
 'grab': np.int64(962),
 'co': np.int64(397),
 'leicest': np.int64(1265),
 'squar': np.int64(2092),
 'base': np.int64(184),
 'children': np.int64(366),
 'book': np.int64(252),
 'author': np.int64(157),
 'parent': np.int64(1577),
 'die': np.int64(595),
 'fire': np.int64(846),
 'taken': np.int64(2192),
 'count': np.int64(497),
 'scheme': np.int64(1923),
 'hand': np.int64(991),
 'fortun': np.int64(879),
 'box offic': np.int64(261),
 'crime': np.int64(511),
 'sequel': np.int64(1966),
 'georg': np.int64(932),
 'robert': np.int64(1861),
 'gone': np.int64(955),
 'ticket': np.int64(2250),
 'studio': np.int64(2144),
 'estim': np.int64(741),
 'crimin': np.int64(512),
 'major': np.int64(1332),
 'week': np.int64(2404),
 'round': np.int64(1874),
 'anim': np.int64(92),
 'express': np.int64(780),
 'tom': np.int64(2264),
 'festiv': np.int64(825),
 'comedi': np.int64(412),
 'christma': np.int64(375),
 'triumph': np.int64(2300),
 'fourth': np.int64(888),
 'open': np.int64(1539),
 'lord': np.int64(1311),
 'ring': np.int64(1854),
 'beat': np.int64(196),
 'total': np.int64(2272),
 'frank': np.int64(893),
 'pack': np.int64(1570),
 'direct': np.int64(602),
 'oscar': np.int64(1556),
 'win': np.int64(2433),
 'director': np.int64(604),
 'steven': np.int64(2116),
 'matt': np.int64(1361),
 'andi': np.int64(89),
 'join': np.int64(1183),
 'cast': np.int64(325),
 'fun': np.int64(907),
 'holiday': np.int64(1041),
 'movi': np.int64(1431),
 'presid': np.int64(1680),
 'distribut': np.int64(619),
 'howev': np.int64(1064),
 'critic': np.int64(514),
 'less': np.int64(1268),
 'project': np.int64(1713),
 'lo': np.int64(1298),
 'angel': np.int64(91),
 'label': np.int64(1222),
 'review': np.int64(1848),
 'york': np.int64(2492),
 'dub': np.int64(663),
 'last week': np.int64(1237),
 'lo angel': np.int64(1299),
 'new york': np.int64(1478),
 'profession': np.int64(1706),
 'declar': np.int64(553),
 'signific': np.int64(2005),
 'american': np.int64(82),
 'institut': np.int64(1130),
 'michael': np.int64(1386),
 'debat': np.int64(546),
 'claim': np.int64(381),
 'hollywood': np.int64(1042),
 'convent': np.int64(474),
 'window': np.int64(2435),
 'death': np.int64(545),
 'tv': np.int64(2311),
 'news': np.int64(1481),
 'refer': np.int64(1792),
 'juli': np.int64(1191),
 'strong': np.int64(2137),
 'juri': np.int64(1194),
 'conclud': np.int64(440),
 'art': np.int64(125),
 'screen': np.int64(1933),
 'credit': np.int64(508),
 'energi': np.int64(715),
 'creat': np.int64(505),
 'charact': np.int64(351),
 'acknowledg': np.int64(13),
 'influenc': np.int64(1114),
 'trend': np.int64(2291),
 'broadcast': np.int64(276),
 'among': np.int64(84),
 'highlight': np.int64(1029),
 'final': np.int64(839),
 'retir': np.int64(1843),
 'rather': np.int64(1766),
 'fear': np.int64(812),
 'person': np.int64(1615),
 'balanc': np.int64(173),
 'integr': np.int64(1132),
 'increasingli': np.int64(1100),
 'ignor': np.int64(1080),
 'question': np.int64(1746),
 'long': np.int64(1305),
 'even': np.int64(749),
 'light': np.int64(1286),
 'channel': np.int64(350),
 'internet': np.int64(1141),
 'draw': np.int64(651),
 'grow': np.int64(978),
 'feder': np.int64(816),
 'commun': np.int64(423),
 'commiss': np.int64(418),
 'threat': np.int64(2241),
 'jackson': np.int64(1169),
 'super': np.int64(2165),
 'effect': np.int64(694),
 'televis': np.int64(2211),
 'rule': np.int64(1881),
 'creativ': np.int64(507),
 'self': np.int64(1954),
 'countri': np.int64(498),
 'free': np.int64(895),
 'refus': np.int64(1797),
 'air': np.int64(57),
 'save': np.int64(1913),
 'privat': np.int64(1697),
 'possibl': np.int64(1661),
 'fine': np.int64(844),
 'long term': np.int64(1306),
 'miss': np.int64(1409),
 'spend': np.int64(2078),
 'jail': np.int64(1170),
 'bond': np.int64(251),
 'money': np.int64(1418),
 'grant': np.int64(967),
 'restrict': np.int64(1839),
 'corner': np.int64(485),
 'lawyer': np.int64(1247),
 'rais': np.int64(1756),
 'incid': np.int64(1095),
 'wednesday': np.int64(2403),
 'accus': np.int64(11),
 'offenc': np.int64(1521),
 'impos': np.int64(1092),
 'rang': np.int64(1759),
 'attend': np.int64(144),
 'drug': np.int64(660),
 'centr': np.int64(334),
 'told': np.int64(2261),
 'abl': np.int64(1),
 'leav': np.int64(1255),
 'firm': np.int64(847),
 'report': np.int64(1820),
 'daili': np.int64(528),
 'local': np.int64(1301),
 'polic': np.int64(1648),
 'station': np.int64(2107),
 'given': np.int64(942),
 'june': np.int64(1193),
 'link': np.int64(1290),
 'respons': np.int64(1837),
 'man': np.int64(1338),
 'univers': np.int64(2330),
 'hospit': np.int64(1050),
 'injuri': np.int64(1119),
 'repres': np.int64(1823),
 'outsid': np.int64(1561),
 'crown': np.int64(519),
 'meet': np.int64(1374),
 'overal': np.int64(1563),
 'highest': np.int64(1027),
 'de': np.int64(541),
 'help': np.int64(1014),
 'revenu': np.int64(1847),
 'relat': np.int64(1807),
 'weve': np.int64(2414),
 'much': np.int64(1448),
 'stronger': np.int64(2138),
 'note': np.int64(1503),
 'made': np.int64(1325),
 'previou': np.int64(1686),
 'away': np.int64(166),
 'king': np.int64(1212),
 'titl': np.int64(2256),
 'figur': np.int64(832),
 'fall': np.int64(797),
 'increas': np.int64(1099),
 'provid': np.int64(1728),
 'aviat': np.int64(162),
 'dicaprio': np.int64(593),
 'howard': np.int64(1062),
 'hugh': np.int64(1066),
 'posit': np.int64(1660),
 'written': np.int64(2474),
 'bill': np.int64(225),
 'said mr': np.int64(1899),
 'last year': np.int64(1238),
 'sister': np.int64(2017),
 'vote': np.int64(2377),
 'compil': np.int64(431),
 'domin': np.int64(632),
 'scene': np.int64(1921),
 'hot': np.int64(1052),
 'park': np.int64(1579),
 'dj': np.int64(622),
 'amaz': np.int64(79),
 'mainstream': np.int64(1330),
 'origin': np.int64(1555),
 'surpris': np.int64(2170),
 'public': np.int64(1730),
 'august': np.int64(153),
 'respect': np.int64(1835),
 'seven': np.int64(1978),
 'fair': np.int64(793),
 'octob': np.int64(1518),
 'chri': np.int64(373),
 'martin': np.int64(1355),
 'glasgow': np.int64(943),
 'ferdinand': np.int64(823),
 'nine': np.int64(1493),
 'town': np.int64(2279),
 'annual': np.int64(94),
 'survey': np.int64(2172),
 'whose': np.int64(2421),
 'latest': np.int64(1242),
 'peter': np.int64(1617),
 'find': np.int64(843),
 'celebr': np.int64(330),
 'becom': np.int64(200),
 'unlik': np.int64(2332),
 'prefer': np.int64(1673),
 'instead': np.int64(1129),
 'run': np.int64(1883),
 'relationship': np.int64(1808),
 'tim': np.int64(2253),
 'support': np.int64(2167),
 'wife': np.int64(2426),
 'teenag': np.int64(2208),
 'jump': np.int64(1192),
 'began': np.int64(201),
 'edward': np.int64(693),
 'young': np.int64(2493),
 'what': np.int64(2415),
 'sensit': np.int64(1961),
 'mother': np.int64(1425),
 'younger': np.int64(2495),
 'anoth': np.int64(95),
 'seriou': np.int64(1968),
 'stori': np.int64(2126),
 'indian': np.int64(1106),
 'offer': np.int64(1522),
 'thompson': np.int64(2237),
 'receiv': np.int64(1781),
 'la': np.int64(1220),
 'opposit': np.int64(1548),
 'pirat': np.int64(1629),
 'golden': np.int64(953),
 'globe': np.int64(946),
 'bafta': np.int64(172),
 'nomin': np.int64(1496),
 'mani': np.int64(1342),
 'think': np.int64(2234),
 'upon': np.int64(2336),
 'friend': np.int64(900),
 'richard': np.int64(1852),
 'adult': np.int64(33),
 'fifth': np.int64(830),
 'child': np.int64(365),
 'french': np.int64(897),
 'previous': np.int64(1688),
 'model': np.int64(1414),
 'theme': np.int64(2229),
 'associ': np.int64(137),
 'classic': np.int64(385),
 'charli': np.int64(356),
 'factori': np.int64(790),
 'might': np.int64(1392),
 'rememb': np.int64(1815),
 'episod': np.int64(733),
 'bbc': np.int64(191),
 'programm': np.int64(1711),
 'fast': np.int64(806),
 'favourit': np.int64(811),
 'two year': np.int64(2315),
 'three year': np.int64(2246),
 'actress': np.int64(21),
 'part': np.int64(1583),
 'version': np.int64(2353),
 'web': np.int64(2400),
 'voic': np.int64(2376),
 'team': np.int64(2204),
 'girl': np.int64(940),
 'mix': np.int64(1411),
 'action': np.int64(17),
 'sinc': np.int64(2013),
 'month': np.int64(1420),
 'ago': np.int64(50),
 'john': np.int64(1181),
 'steve': np.int64(2115),
 'ten': np.int64(2213),
 'old': np.int64(1529),
 'gari': np.int64(920),
 'begin': np.int64(202),
 'australia': np.int64(154),
 'copi': np.int64(482),
 'publish': np.int64(1732),
 'yet': np.int64(2491),
 'reveal': np.int64(1846),
 'year old': np.int64(2488),
 'product': np.int64(1705),
 'law': np.int64(1244),
 'affect': np.int64(41),
 'fund': np.int64(909),
 'tax': np.int64(2199),
 'reduc': np.int64(1790),
 'sourc': np.int64(2059),
 'britain': np.int64(272),
 'govern': np.int64(961),
 'close': np.int64(393),
 'investor': np.int64(1147),
 'advantag': np.int64(35),
 'coupl': np.int64(499),
 'reduct': np.int64(1791),
 'tradit': np.int64(2282),
 'shoot': np.int64(1992),
 'period': np.int64(1614),
 'drama': np.int64(649),
 'isnt': np.int64(1159),
 'anyth': np.int64(100),
 'replac': np.int64(1819),
 'execut': np.int64(767),
 'budget': np.int64(285),
 'similar': np.int64(2008),
 'level': np.int64(1273),
 'vera': np.int64(2351),
 'drake': np.int64(648),
 'love': np.int64(1316),
 'worst': np.int64(2462),
 'strength': np.int64(2132),
 'pound': np.int64(1666),
 'dollar': np.int64(628),
 'result': np.int64(1840),
 'shot': np.int64(1996),

In [12]:
y = pd.get_dummies(df['labels'])
y = y.iloc[:,0].values

In [13]:
y.shape

(2225,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.naive_bayes import MultinomialNB
labels = MultinomialNB().fit(x_train,y_train)
y_pre = labels.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pre))
print(classification_report(y_test,y_pre))

[[331  11]
 [  2 101]]
              precision    recall  f1-score   support

       False       0.99      0.97      0.98       342
        True       0.90      0.98      0.94       103

    accuracy                           0.97       445
   macro avg       0.95      0.97      0.96       445
weighted avg       0.97      0.97      0.97       445

### Vectorization