In [1]:
import pandas as pd 
import re
import nltk

In [2]:
data = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\NLP techadd\file_name.csv")
data.head()

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Text,Date Created
0,"No matter who someone is, how they look like, ...",Liberal,1,t5fybt,socialism,https://v.redd.it/ng5fyl7hp2l81,0,NaN,1.646272e+09
1,Biden speech draws 38.2 million U.S. TV viewers,Liberal,6,t5fqdn,democrats,https://www.reuters.com/world/us/biden-speech-...,1,NaN,1.646271e+09
2,State of the union,Liberal,1,t5fj9a,DemocraticSocialism,https://www.reddit.com/r/DemocraticSocialism/c...,1,Who watched the state of the union last night ...,1.646270e+09
3,We Should Just Give Poor People Money,Liberal,7,t5f7n9,SocialDemocracy,https://youtu.be/a80kRjpubG0,3,NaN,1.646270e+09
4,Do it for the Dew,Liberal,6,t5es2c,democrats,https://i.redd.it/drmunn90f2l81.jpg,1,NaN,1.646268e+09

In [3]:
data.describe()

              Score  Num of Comments  Date Created
count  12854.000000     12854.000000  1.285400e+04
mean     118.558270        19.055936  1.622576e+09
std      498.888034        60.381567  6.112838e+07
min        0.000000         0.000000  1.231048e+09
25%        3.000000         1.000000  1.632132e+09
50%       12.000000         3.000000  1.642030e+09
75%       65.000000        15.000000  1.645107e+09
max    25055.000000      2150.000000  1.646272e+09

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12854 entries, 0 to 12853
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            12854 non-null  str
 1   Political Lean   12854 non-null  str
 2   Score            12854 non-null  int64
 3   Id               12854 non-null  str
 4   Subreddit        12854 non-null  str
 5   URL              12854 non-null  str
 6   Num of Comments  12854 non-null  int64
 7   Text             2428 non-null   str
 8   Date Created     12854 non-null  float64
dtypes: float64(1), int64(2), str(6)
memory usage: 903.9 KB

In [5]:
data.shape

(12854, 9)

In [6]:
data.sample()

,Title,Political Lean,Score,Id,Subreddit,URL,Num of Comments,Text,Date Created
12692,Give this to friends who want to be cops,Conservative,0,2wo1qt,anarchocapitalism,https://www.reddit.com/r/anarchocapitalism/com...,2,Turn Away From the State\n\nWhy do you want to...,1.424537e+09

In [7]:
data.isna().sum()

Title                  0
Political Lean         0
Score                  0
Id                     0
Subreddit              0
URL                    0
Num of Comments        0
Text               10426
Date Created           0
dtype: int64

In [8]:
data =data.drop('Text',axis=True)

In [9]:
data.index

RangeIndex(start=0, stop=12854, step=1)

In [10]:
data.dtypes

Title                  str
Political Lean         str
Score                int64
Id                     str
Subreddit              str
URL                    str
Num of Comments      int64
Date Created       float64
dtype: object

In [11]:
nltk.download('punkt')
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Error loading punkt: <urlopen error pathsec.urlopen: no
[nltk_data]     validated address for host
[nltk_data]     'raw.githubusercontent.com'; refusing to connect by
[nltk_data]     unvalidated hostname>
[nltk_data] Error loading stopwords: <urlopen error pathsec.urlopen:
[nltk_data]     no validated address for host
[nltk_data]     'raw.githubusercontent.com'; refusing to connect by
[nltk_data]     unvalidated hostname>

In [12]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+"," ",text)
    text = re.sub(r"[a-Az-Z]\s"," ",text)
    text = word_tokenize(text)
    words = [word for word in words if word not in stopwords]
    words = [lemmatizer.lemmatize(words)for word in words]

    return ' '.join(words)

In [13]:
clean_text

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(
    max_features=8000,
    ngram_range=(2,3),
    stop_words='english',
    min_df=3
)
x = tfidf.fit_transform(data['Title'])

In [16]:
from sklearn.preprocessing import LabelEncoder
le  =LabelEncoder()
y= le.fit_transform(data['Title'])
y

array([6685, 1602, 8575, ..., 6307, 3505, 2007], shape=(12854,))

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.8,random_state=42)

In [18]:
from sklearn.naive_bayes import MultinomialNB
NB= MultinomialNB()
NB.fit(x_train,y_train)

MultinomialNB()

In [19]:
y_pred = NB.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.00019447685725398678